# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dccprint < Formula
  desc "Una herramienta TUI para imprimir archivos en el DCC."
  homepage "https://github.com/fgonzalezurriola/dccprint"
  version "0.1.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.5/dccprint_Darwin_x86_64.tar.gz"
      sha256 "cd9e166a391c9b752274b2b204a0242b69c4109fa7e210ba04e26bc9b50ffda1"

      def install
        bin.install "dccprint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.5/dccprint_Darwin_arm64.tar.gz"
      sha256 "4ca31d769f8398762a45ce31dd0baff6cdc26e98b9c0df896482e4bac2f02aa0"

      def install
        bin.install "dccprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.5/dccprint_Linux_x86_64.tar.gz"
      sha256 "7cd5e0f6630bd97e17b95ef82d32bfd04306ffc08018a75d1f8333f2ade04ab5"
      def install
        bin.install "dccprint"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.5/dccprint_Linux_arm64.tar.gz"
      sha256 "0138c082233101001706efe8b34dceef91b1b028c137edc8176ef084dbe4890a"
      def install
        bin.install "dccprint"
      end
    end
  end
end
