# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dccprint < Formula
  desc "Una herramienta TUI paraa imprimir archivos en el DCC."
  homepage "https://github.com/fgonzalezurriola/dccprint"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.0/dccprint_Darwin_x86_64.tar.gz"
      sha256 "6f55584828e620666bb96d3bce99945950423c0791961c925d4e2c8300904d88"

      def install
        bin.install "dccprint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.0/dccprint_Darwin_arm64.tar.gz"
      sha256 "bd35388d2bb470ff8b00a6ef73186eea2c49f248d37dfaff2e412cb81ce5bfb8"

      def install
        bin.install "dccprint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.0/dccprint_Linux_x86_64.tar.gz"
      sha256 "4520f22e28fe633fe054fffcdc12c9c464920348cbe90209342f5fb3497c7aec"
      def install
        bin.install "dccprint"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.0/dccprint_Linux_arm64.tar.gz"
      sha256 "e1419c086780116f8a78c0e7671f6b44a49ac3152e52a40e75843c56f8b14cfc"
      def install
        bin.install "dccprint"
      end
    end
  end
end
