# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dccprint < Formula
  desc "Una herramienta TUI paraa imprimir archivos en el DCC."
  homepage "https://github.com/fgonzalezurriola/dccprint"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.1/dccprint_Darwin_x86_64.tar.gz"
      sha256 "f463569d160d6151d823fa5b969c9772aa982f1b7152d0474bf29501a7e8a254"

      def install
        bin.install "dccprint"
      end
    end
    on_arm do
      url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.1/dccprint_Darwin_arm64.tar.gz"
      sha256 "eeed94f00ec5e2ad9dd12253369059a7818cdfdd7fb1eb5c06b941753e8f1781"

      def install
        bin.install "dccprint"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.1/dccprint_Linux_x86_64.tar.gz"
        sha256 "0a89a821cd1420b0cc5d87dd349a9493dddd199c3b4efc82ebebdd23d5ee30bd"

        def install
          bin.install "dccprint"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fgonzalezurriola/dccprint/releases/download/v0.1.1/dccprint_Linux_arm64.tar.gz"
        sha256 "331f876a9a8b4f61163754d1cbc5f9ab046b790a257a73ac16ec82af7c617990"

        def install
          bin.install "dccprint"
        end
      end
    end
  end
end
